version: '3.9'

services:
  app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/app
    command: sh -c "python manage.py && python run.py"
    
